version: '3'
services:
  db:
    container_name: postgresdb
    image: postgres
    volumes:
      - psqldb:/var/lib/postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_wallet
    networks:
      - projectwallet
volumes:
  psqldb:
networks:
  projectwallet:
